In [12]:
import pandas as pd
import seaborn as sns
from lib.visualize import get_fig_axes

ImportError: cannot import name 'get_fig_axes' from 'lib.visualize' (/work/src/lib/visualize.py)

## Traindata

In [3]:
tl_df = pd.read_csv("/work/data/input/nfl-health-and-safety-helmet-assignment/train_labels.csv");

In [ ]:
home_tl_df = tl_df[tl_df["label"].str.contains("H")]
visit_tl_df = tl_df[tl_df["label"].str.contains("V")]

In [11]:
counter = 0;
fig, axes = get_fig_axes(2,1,(15,10));

sns.displot(home_tl_df["label"],ax=axes[0])
sns.displot(visit_tl_df["label"],axes[1])

NameError: name 'get_fig_axes' is not defined

In [29]:
ss = pd.read_csv("/work/data/input/nfl-health-and-safety-helmet-assignment/sample_submission.csv")
ss["video"] = ss["video_frame"].apply(lambda x:x.split("_")[0])
ss["frame"] = ss["video_frame"].apply(lambda x:x.split("_")[1])


helmets = pd.read_csv("/work/data/input/nfl-health-and-safety-helmet-assignment/test_baseline_helmets.csv")
tracking = pd.read_csv("/work/data/input/nfl-health-and-safety-helmet-assignment/test_player_tracking.csv")


#helmets["video"] = ss["video_frame"].apply(lambda x:x.split("_")[0])
#ss["frame"] = ss["video_frame"].apply(lambda x:x.split("_")[1])

In [31]:
ss

                    video_frame label  left  width  top  height  video   frame
0        57906_000718_Endzone_1   H22     1      1    1       1  57906  000718
1        57906_000718_Endzone_2   H22     1      1    1       1  57906  000718
2        57906_000718_Endzone_3   H22     1      1    1       1  57906  000718
3        57906_000718_Endzone_4   H22     1      1    1       1  57906  000718
4        57906_000718_Endzone_5   H22     1      1    1       1  57906  000718
...                         ...   ...   ...    ...  ...     ...    ...     ...
2659  58102_002798_Sideline_362   H22     1      1    1       1  58102  002798
2660  58102_002798_Sideline_363   H22     1      1    1       1  58102  002798
2661  58102_002798_Sideline_364   H22     1      1    1       1  58102  002798
2662  58102_002798_Sideline_365   H22     1      1    1       1  58102  002798
2663  58102_002798_Sideline_366   H22     1      1    1       1  58102  002798

[2664 rows x 8 columns]

In [30]:
tracking

,gameKey,playID,player,time,x,y,s,a,dis,o,dir,event
0,57906,718,H55,2019-09-08T17:29:28.700Z,11.92,30.08,2.15,0.80,0.22,112.10,89.85,huddle_start_offense
1,57906,718,H55,2019-09-08T17:29:28.799Z,12.14,30.07,2.07,1.06,0.21,108.40,91.43,NaN
2,57906,718,H55,2019-09-08T17:29:28.900Z,12.34,30.06,1.97,1.22,0.20,104.14,92.42,NaN
3,57906,718,H55,2019-09-08T17:29:29.000Z,12.53,30.05,1.85,1.30,0.19,100.61,93.22,NaN
4,57906,718,H55,2019-09-08T17:29:29.099Z,12.71,30.04,1.75,1.30,0.18,97.01,93.86,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
19264,58102,2798,V78,2019-12-08T23:10:20.099Z,62.99,17.54,2.47,2.16,0.26,146.35,133.90,NaN
19265,58102,2798,V78,2019-12-08T23:10:20.200Z,63.15,17.36,2.28,2.12,0.24,149.20,135.83,NaN
19266,58102,2798,V78,2019-12-08T23:10:20.299Z,63.30,17.20,2.08,2.04,0.22,150.95,137.14,NaN
19267,58102,2798,V78,2019-12-08T23:10:20.400Z,63.43,17.06,1.86,1.99,0.19,149.29,137.62,tackle
19268,58102,2798,V78,2019-12-08T23:10:20.500Z,63.54,16.93,1.65,1.91,0.17,144.53,139.11,NaN

In [27]:
#ss[(ss["video"]=="57906" )& ss["video_frame"].str.contains("Endzone")]["frame"]
display(len(ss["frame"].unique()))
display(len(ss["video"].unique()))

3

3

In [28]:
helmets

                     video_frame  left  width  top  height      conf
0        58102_002798_Sideline_1   402     18  418      20  0.488037
1        58102_002798_Sideline_1   373     21  430      23  0.748047
2        58102_002798_Sideline_1   711     20  405      21  0.827148
3        58102_002798_Sideline_1   392     21  452      22  0.829590
4        58102_002798_Sideline_1   457     19  366      23  0.837402
...                          ...   ...    ...  ...     ...       ...
72381  57995_000109_Sideline_529   987     18  248      19  0.866699
72382  57995_000109_Sideline_529   524     20  530      20  0.868164
72383  57995_000109_Sideline_529   118     22  588      20  0.870117
72384  57995_000109_Sideline_529   300     20  620      20  0.872559
72385  57995_000109_Sideline_529   270     18  421      19  0.879883

[72386 rows x 6 columns]